# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
default: &defaults
  docker:
      - image: circleci/node:13.8.0
commands:
  print_pipeline_id:
    description: Command to print the id of the current pipeline
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  failed_job:
    <<: *defaults
    steps:
      - print_pipeline
      - run:
          name: Run after failure
          command: |
            echo "Failed successfully" 
          when: on_fail
  print_from_command:
    <<: *defaults
    steps: 
      - print_pipeline_id
    
  save_hello_world_output:
    <<: *defaults
    steps:
      - run:
          name: "output hello world to a text file"
          command: |
            echo "Hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
workflows:
  test_workflow:
    jobs:
      - print_from_command
      - failed_job
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
     
